### PR TITLE
Test labeler workflow (README)

### PR DESCRIPTION
**Pull request by shrihanDev**
## Changes
in volcareso/volcareso.js, I have: 
- just added a new line for testing the labeler pull request workflow

## I have:
- [ ] fixed a typo
- [ ] fixed a bug
- [ ] added a feature
- [ ] added docs
- [x] tweaked something else ( I have described it above )
(Did nothing any considerable)

### CODE REVIEW

**Comment by shrihanDev** [comment]
So it didn't work, hmm....

**Comment by shrihanDev** [comment]
Oh well, turns out, this is an issue after all. See actions/labeler#12

**Comment by shrihanDev** [comment]
@volcareso Waiting for your input

**Comment by volcareso** [comment]
Idk what to do
It was perfectly fine yesterday

**Comment by volcareso** [comment]
[it worked](https://github.com/volcareso/volcareso.js/pull/18)

**Comment by shrihanDev** [comment]
Please have a look at the conversation in actions/labeler#12. This works for those having write access to the repository, but not for forks, i.e. if you create pull requests, it will work, but not for me, as I don't have write access. This is actually intended; the GitHub Token works like this.

**Comment by volcareso** [comment]
I saw that

**Pull request closed without merging**
